### ISSUE TITLE
Anet_videos_15fps_short256/missing_files.txt

### ISSUE THREAD

**Issue by tqosu** [sming256/OpenTAD#12]
Hi Shuming,

Did you upload Anet_videos_15fps_short256/missing_files.txt?

FileNotFoundError: [Errno 2] No such file or directory: 'data/activitynet-1.3/raw_data/Anet_videos_15fps_short256/missing_files.txt'

I downloaded [Update]_Anet_videos_15fps_short256.zip, but there was no missing_files.txt.

Where can I find it?

Thanks.

**Comment by tqosu** [comment]
Can I place an empty file there?

**Comment by sming256** [comment]
Sorry that I forget to upload it. It's just an empty file if using `Anet_videos_15fps_short256` video. 
You can also just set `block_list=None`.

**Comment by tqosu** [comment]
Thanks.
