### ISSUE TITLE
feature_stride vs sample_stride

### ISSUE THREAD

**Issue by tqosu** [sming256/OpenTAD#14]
Should I use feature_stride or sample_stride?
Or both?

**Comment by tqosu** [comment]
Can I say the feature is always uniformly sampled?

**Comment by sming256** [comment]
What does a `uniformly sampled feature` mean?

**Comment by tqosu** [comment]
For a given sampled sequence, the distance between two neighboring sampled feature indexes is always a constant.

**Comment by sming256** [comment]
Yes. The distance between two neighboring features is always the same.

**Comment by tqosu** [comment]
Thanks.
