### ISSUE TITLE
position of the adapter

### ISSUE THREAD

**Issue by zhangwen666666** [sming256/OpenTAD#15]
Thank you for your outstanding work! How to train adapters in TAD models outside the backbone network

**Comment by sming256** [comment]
Thanks for your interest! We will release the code and pretrained checkpoints for the side-tuning adapter next month.

**Comment by sming256** [comment]
The side tuning model is released [here](https://github.com/sming256/OpenTAD/blob/main/opentad/models/backbones/vit_ladder.py). We also provide a training example [here](https://github.com/sming256/OpenTAD/blob/main/configs/adatad/thumos/e2e_thumos_videomaev2_g_768x2_224_side_2e-4.py) .

**Comment by zhangwen666666** [comment]
Thank you！Your work has been extremely beneficial to me.
