### ISSUE TITLE
adatad on multithumos

### ISSUE THREAD

**Issue by Jmh0527** [sming256/OpenTAD#18]
I noticed that the performance of adatad on the multi-label dataset (multithumos) has not been reported. Can you tell me what its mAP is ？

**Comment by sming256** [comment]
We are running the experiments and will update the results soon.

**Comment by sming256** [comment]
Hi @Jmh0527, we release AdaTAD's results on Multi-THUMOS at [here](../../configs/adatad/README.md#multi-thumos-results). The performance is the following.

|   Backbone   | Frames | Img Size | mAP@0.2 | mAP@0.5 | mAP@0.7 | ave. mAP (0.1:0.9:0.1) |
| :----------: | :----: | :------: | :-----: | :-----: | :-----: | :--------------------: |
|  VideoMAE-S  |  768   |   160    |  61.34  |  46.74  |  26.88  |         40.77          |
|  VideoMAE-B  |  768   |   160    |  63.90  |  48.74  |  28.72  |         42.76          |
|  VideoMAE-L  |  768   |   160    |  66.06  |  51.80  |  31.73  |         45.15          |
|  VideoMAE-H  |  768   |   160    |  67.20  |  52.99  |  32.70  |         46.02          |
| VideoMAEV2-g |  768   |   160    |  68.23  |  53.87  |  33.03  |         46.74          |
| VideoMAEV2-g |  1536  |   224    |  71.11  |  55.83  |  34.86  |         48.73          |
