### ISSUE TITLE
VisionTransformerCP vs VisionTransformerLadder

### ISSUE THREAD

**Issue by tqosu** [sming256/OpenTAD#20]
Hi Shuming,

What are VisionTransformerCP and VisionTransformerLadder?

Thanks.

**Comment by sming256** [comment]
`VisionTransformerCP` is the rewrite of the official VisionTransformer used in VideoMAE, but supports activation checkpointing (`with_cp=True`).

`VisionTransformerLadder` is the side-tuning architecture of VideoMAE, which is introduced in [AdaTAD Figure 5](https://arxiv.org/pdf/2311.17241).

**Comment by tqosu** [comment]
Thanks.
