### ISSUE TITLE
conv1d in vit_adapter

### ISSUE THREAD

**Issue by Jmh0527** [sming256/OpenTAD#23]
Thanks for your excellent work. I notice that conv1d is used in the adapter of adatad (opentad/models/backbone/vit_adapter). Why didn't you try conv3d?

**Comment by sming256** [comment]
Thanks for your question!

In fact, we ablated the kernel size and tried conv3d (see Table 13 in [supplementary](https://arxiv.org/pdf/2311.17241v2)). We find that introducing spatial convolution would decrease the performance and increase the memory usage. We suspect that the original backbone has effectively handled the spatial context, and additional spatial processing could potentially disrupt the pretrained knowledge.

**Comment by Jmh0527** [comment]
Actually, I think that when using dwconv, a conv with a 1x1 kernel should be applied before to capture information between channels. I recall a paper that employed this approach, although I can't remember the specific one. What do you think?
