### ISSUE TITLE
Bug in optimizer

### ISSUE THREAD

**Issue by LatteCatcat** [sming256/OpenTAD#26]
<img width="503" alt="Screen Shot 2024-07-10 at 11 22 13 PM" src="https://github.com/sming256/OpenTAD/assets/128436897/f0bab6ef-1291-48c8-b097-e11d2e53e62d">
Line 72 in optimizer.py could be problematic if you try to add two or more names in the custom_name list, for this kind of list will automatically repeat itself. If you change it to **[[] for _ in custom_name_list]**, it would work.

**Comment by sming256** [comment]
Thanks for your great feedback! 

I will fix this bug in the next release.

**Comment by sming256** [comment]
Bug has been fixed.
