### ISSUE TITLE
A mistake in code design

### ISSUE THREAD

**Issue by nohi191212** [sming256/OpenTAD#33]
See ./configs/_base_/models/tadtr.py

There are two 'num_classes' in line 15 and in line 53.

If we want to use a subset of dataset, we have to change this param twice, like this:
![image](https://github.com/user-attachments/assets/81a03b57-feb8-4814-a9ab-6c50cca63e1e)

This design is a little bit strange.

**Comment by sming256** [comment]
Thanks for your suggestion.

Currently, the number of classes in DETR's transformer and loss are decoupled. We will consider improving this in the next release.
