### ISSUE TITLE
Training and testing commands

### ISSUE THREAD

**Issue by yilonghe** [sming256/OpenTAD#38]
If I want to use the extracted features you open-sourced, what are the commands for training and testing, respectively?

**Comment by sming256** [comment]
You can refer to [here](https://github.com/sming256/OpenTAD/tree/main/configs/actionformer#train) and [here](https://github.com/sming256/OpenTAD/blob/main/docs/en/usage.md) for detailed command of training and testing.

For example, you can use the following command to launch the feature-based training with ActionFormer.
`torchrun --nnodes=1 --nproc_per_node=1 --rdzv_backend=c10d --rdzv_endpoint=localhost:0 tools/train.py configs/actionformer/anet_tsp.py
`
