### ISSUE TITLE
TypeError: softnms(): incompatible function arguments.

### ISSUE THREAD

**Issue by zippyzzzlz** [sming256/OpenTAD#40]
When I train adatad on the thumos dataset and execute the calculation of softnms, an error occurs: TypeError: softnms(): incompatible function arguments.The detailed error message is as follows:

> Traceback (most recent call last):
>
>   File "/home/zippyzzzlz/OpenTAD/tools/train.py", line 229, in <module>
>         main()
>
>   File "/home/zippyzzzlz/OpenTAD/tools/train.py", line 214, in main
>         eval_one_epoch(
>
>   File "/home/zippyzzzlz/OpenTAD/tools/../opentad/cores/test_engine.py", line 68, in eval_one_epoch
>     result_dict = gather_ddp_results(world_size, result_dict, cfg.post_processing)
>
>   File "/home/zippyzzzlz/OpenTAD/tools/../opentad/cores/test_engine.py", line 116, in gather_ddp_results
>     segments, scores, labels = batched_nms(segments, scores, labels, **post_cfg.nms)
>
>   File "/home/zippyzzzlz/OpenTAD/tools/../opentad/models/utils/post_processing/nms/nms.py", line 139, in batched_nms
>     sorted_segs, sorted_scores, sorted_cls_idxs = SoftNMSop.apply(
>
>   File "/home/zippyzzzlz/anaconda3/envs/opentad/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
>     return super().apply(*args, **kwargs)  # type: ignore[misc]
>
>   File "/home/zippyzzzlz/OpenTAD/tools/../opentad/models/utils/post_processing/nms/nms.py", line 41, in forward
>     inds = nms_1d_cpu.softnms(
>
> TypeError: softnms(): incompatible function arguments. The following argument types are supported:
>     1. (segs: torch.Tensor, scores: torch.Tensor, dets: torch.Tensor, iou_threshold: float, sigma: float, min_score: float, method: int) -> torch.Tensor

It seemed like there was a type mismatch in the function, so I added a breakpoint to debug. The attached image shows the data types of all variables just before the error occurred. The types seemed to be correct.

Then I commented out the line `"t1=float(t1),t2=float(t2)," `in the function and found that the code could run successfully. 

![problem](https://github.com/user-attachments/assets/a0c47b4f-1c04-4da2-8091-7c9974e8248f)

Is my approach correct and reasonable?

**Comment by sming256** [comment]
Thanks for your question!

First, `t1` and `t2` are only used for temporal action proposal generation methods, such as BMN. So, commenting on these two lines is fine for AdaTAD.

Second, the code should work properly if you install the `nms-1d-cpu` from OpenTAD repo.  
Can try `pip install opentad/models/utils/post_processing/nms` again to make sure you install it correctly and run the inference again?

**Comment by zippyzzzlz** [comment]
Thank you very much for your patient explanation! 

I was able to successfully run the inference after installing `nms-1d-cpu.`
