### ISSUE TITLE
Where is the Anet_videos_15fps_short256.zip file

### ISSUE THREAD

**Issue by hwenwur** [sming256/OpenTAD#43]
In activitynet/README.md
```
[Update] We have recently added a processed version of the ActivityNet-v1.3 videos to the folders above, named Anet_videos_15fps_short256.zip. The video has been converted by ffmpeg to 15 fps, and the shorter side of the video is resized to 256 pixels. In this codebase, all end-to-end ActivityNet experiments are based on this data.
```

I cann't find any url for this, How do I download the `Anet_videos_15fps_short256.zip`?

Thank you very much!

**Comment by sming256** [comment]
After you fill out the data [request form](https://docs.google.com/forms/d/e/1FAIpQLSdxhNVeeSCwB2USAfeNWCaI9saVT6i2hpiiizVYfa3MsTyamg/viewform), you should get the link to this data within 24 hours.
