### ISSUE TITLE
video_anno["gt_segments"] 计算存在bug

### ISSUE THREAD

**Issue by hwenwur** [sming256/OpenTAD#45]
https://github.com/sming256/OpenTAD/blob/15f5c44e69fbbd9b3a7b82267314364df87d7852/opentad/datasets/thumos.py#L89
```
video_anno["gt_segments"] = video_anno["gt_segments"] - self.offset_frames
video_anno["gt_segments"] = video_anno["gt_segments"] / self.snippet_stride
```
video_anno["gt_segments"] 底层数组有概率出现浅拷贝，导致不同epoch重复调用时，gt_segments在上一轮的基础上再次 `- offset_frames` 和 `/ self.snippet_stride`

调试了一晚上才发现，目前不确定概率的高低

**Comment by sming256** [comment]
Thanks for your suggestion. A possible solution might be 
```
    if video_anno != {}:
        video_anno = deepcopy(video_anno)
        video_anno["gt_segments"] = video_anno["gt_segments"] - self.offset_frames
        video_anno["gt_segments"] = video_anno["gt_segments"] / self.snippet_stride
```

Can you tell me how to reproduce the error? Or can you help to check whether the above modification solves the bug?

**Comment by hwenwur** [comment]
不好意思，英语一般，下面用中文描述。

经过进一步排查，之前对这个问题的解释有误，此处一直是浅拷贝，但是由于pytorch DataLoader的数据加载机制，偶然避开了这个问题。

## 复现方式
将`configs/temporalmaxer/thumos_i3d.py`中的 num_workers 改成 0 可以稳定触发该bug，运行对应配置可以稳定触发该问题。

## 原因
DataLoader通过创建子进程加载数据，如果每轮epoch后子进程被销毁，下一轮再重建，则不会出现这个问题。如果子进程被复用，那么 `gt_segments` 的值就会在上一轮的基础上，再次` - offset_frames` 和 `/ self.snippet_stride`

**Comment by sming256** [comment]
非常感谢你的反馈！这的确是一个严重的bug。
强制深拷贝`video_anno = deepcopy(video_anno)`可以解决这个问题。我会立即修复。
感谢感谢！

**Comment by sming256** [comment]
The bug has been fixed.
