### ISSUE TITLE
How to get the classifier files of activitynet

### ISSUE THREAD

**Issue by Wenju-Huang** [sming256/OpenTAD#5]
such as cuhk_val_simp_7.json new_3ensemble_uniformerv2_large_only_global_anet_16x10x3.json

**Comment by Wenju-Huang** [comment]
If I run a test video that is not in the ActivityNet, how should I modify the post_processing part

**Comment by sming256** [comment]
In this case, if you are using an ActivityNet-pretrained TAD model, you need 
1. Generate the video classification result of this video by yourself. Save it in JSON with a similar format in the provided classifier.
2. Change the JSON file in the post-processing to your generated file.

We are planning to release an end-to-end HACS-pretrained TAD model without an external classifier. I think this model will be more suitable for zero-shot testing.
