### ISSUE TITLE
Adatad train issue

### ISSUE THREAD

**Issue by fy-shen** [sming256/OpenTAD#50]
[log1219.json](https://github.com/user-attachments/files/18205471/log1219.json)
[log_raw.json](https://github.com/user-attachments/files/18205481/log_raw.json)
I compared my training log with the one provided by the author. The parameters are basically the same, but the model cannot converge. I hope you can help me analyze the reason. Thank you very much.

**Comment by sming256** [comment]
I think you need to double-check
(1) whether the VideoMAE-pretrained model is correctly loaded. Please check [here](https://github.com/sming256/OpenTAD/tree/main/configs/adatad#prepare-the-pretrained-videomae-checkpoints).
(2) whether your THUMOS data is correct. You can use the released checkpoint to do the inference only. If you can not get a similar performance, your raw video could have some problems.

**Comment by fy-shen** [comment]
Thanks for your reply, I found that it was indeed the pre-trained model that was wrong, the file name was the same but the size was different
