### ISSUE TITLE
VideoMAE model conversion script

### ISSUE THREAD

**Issue by talda** [sming256/OpenTAD#51]
Hi,

I could not locate a script to convert models trained using VideoMAE to use with OpenTAD. I see only converter for VideoMAE2 models.

Is it possible to add it to this repo?

Thank you.

**Comment by sming256** [comment]
The conversion script has been uploaded [here](https://github.com/sming256/OpenTAD/blob/main/tools/model_converters/convert_videomae_finetuned.py). You can run the following command to convert the model.

```bash
python tools/model_converters/convert_videomae_finetuned.py \
    videomae_release_checkpoint.pth vit-base-p16_videomae-k400-pre_16x4x1_kinetics-400_my.pth --arch base
```

Note that we also have released converted checkpoints [here](https://github.com/sming256/OpenTAD/blob/main/configs/adatad/README.md#prepare-the-pretrained-videomae-checkpoints).
