### ISSUE TITLE
Cannot use gdown to download Anet raw video data

### ISSUE THREAD

**Issue by maojiaqi111** [sming256/OpenTAD#6]
When I use this command to download _Anet_videos_15fps_short256.zip from google drive.
```
gdown [download link]
```
I got this error:
```
Failed to retrieve file url:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.
        Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

        [download link]

but Gdown can't. Please check connections and permissions.
```
Could you please change the permission to 'Anyone with the link'?

**Comment by sming256** [comment]
Thanks for your interest! However, ActivityNet data is only available under the license agreement so far. Thus, we can not make it public for everyone. You can try to download the data through:

1. Web browser. While it can not resume from break-point.
2. Baidu Cloud.
3. [Gdrive](https://github.com/glotlabs/gdrive) to download from the terminal.
4. Google Drive PC client.
